:toc: macro
:toc-title: Tabla de Contenidos
:toclevels: 99

# Guía para el buen curriculum vitae

En este pequeño documento se detallarán tips para que tengas un buen curriculum. Además de algunas formas
para detectar y filtrar trabajos que quizás no sean los más convenientes para tu desarrollo profesional/personal.

toc::[]

## Herramientas

Se recomiendan las siguientes herramientas para simplificar el proceso de elaboración de un curriculum.

### AsciiDoc

Para elaborar estos documentos se recomienda https://asciidoctor.org[AsciiDoc]. Un formato similar a https://guides.github.com/features/mastering-markdown/[Markdown] pero con mayor cantidad de funciones, por ejemplo la generación de una tabla de contenidos automática.

### Resume.io

https://resume.io/[Resume.io] es un sitio web para elaborar curriculums vistozos y coloridos. Es recomendado como un complemento para estos documentos.

### GitHub

Facilita la edición y control de versiones de los documentos. Es recomendable que hagas `fork` de este repositorio y lo configures como privado para su posterior edición. Aunque igualmente puedes utilizar otro proveedor o tener un repositorio local. Lo importante es tener los documentos bajo control de versiones.

## Estructura

Para elaborar un curriculum se recomiendan diversos archivos separados por su contexto y función. Los siguientes son las recomendaciones básicas, pero puedes adaptarlo a tus necesidades.

### cv.adoc

Este archivo es el principal, contiene toda la información de tu experiencia profesional, todo trabajo, evento, certificación, entre otros en que hayas participado debe estar aquí. Debe contener una tabla de contenidos y ser actualizado periódicamente (normalmente a fin de cada mes) incluyendo lo más detallado posible las actividades que haz realizado. Este es el documento maestro que debe ser usado para generar los otros documentos. Esto debe ser por que la memoria es frágil y es conveniente tener una referencia detallada de todo lo realizado para poder explicar mejor los logros alcanzados en el momento de una entrevista.

Para elaborar una tabla de contenidos automática puedes usar:

```adoc
:toc: macro
:toc-title: Tabla de Contenidos
:toclevels: 99

# Título del Documento

toc::[]

## Sección 1
### Sección 1-a
#### Sección 1-a-b

```

### resume.adoc

Este archivo es un pequeño resumen del `cv.adoc`. Debe ser adaptado según el trabajo al que se postula. Incluir solamente las actividades relevantes. Se debe actualizar cuando sea necesario. Se recomienda crear un archivo dependiendo del área que se quiera destacar. Por ejemplo un resumen orientado a trabajos para desarrollador iOS puede ser `resume-ios.adoc`. Copiar y pegar la información `cv.adoc` que se necesite y resumirla. Debe contener mínimo una y máximo tres páginas. El Número ideal es de dos páginas.

### cover.adoc

Este archivo es una referencia personal. Incluye un perfil de lo que buscas como profesional y como podrías aportar a la empresa a la que postulas. Ayuda a las personas que te entrevistarán a determinar si eres un candidato que encaje en su cultura empresarial. Se recomienda tener un `cover.adoc` general y luego crear archivos separados para la empresa que se quiera postular (Ejemplo: `cover-empresa1.adoc`). Se debería investigar los proyectos en que la empresa ha participado y cómo las habilidades que tienes podrían ser usadas para proyectos similares futuros.

## Flujo de Trabajo

Muchas personas prefieren utilizar sistemas como https://www.linkedin.com/[Linkedin] o un simple documento `pdf` para elaborar su curriculum. Puede que sean útiles para personas no técnicas, pero si tu tienes las habilidades necesarias para utilizar _Github_, entonces puedes beneficiarte de las herramientas nombradas anteriormente.

El flujo seguiría una serie de pasos similares a lo siguiente: 

. El primero es actualizar el archivo `cv.adoc` constantemente. 
. Al momento de querer cambiar de empresa o proyecto es cuando se debe crear o actualizar el archivo `resume.adoc` y `cover.adoc`. 
. Finalmente se pueden utilizar el comando `$ asciidoctor-pdf cv.adoc` para generar un archivo `pdf` entregable.
. Si se desea se puede actualizar _LinkedIn_ o _Resume.io_ para obtener un formato distinto al posible con _AsciiDoc_.

La utilización de _LinkedIn_ o _Resume.io_ es totalmente opcional, aunque recomendable, para poder tener la información disponible en diferentes formatos o redes sociales.

Asegurate siempre de que algún amigo revise la redacción, gramática y ortografía de tu curriculum antes de enviarlo. Este es un documento que debe ser lo más profesional, pulcro y bien redactado posible.

## Idioma Inglés y Texto Plano

¿Por qué privilegiar texto plano e inglés?. Principalmente por que algunas empresas (normalmente del primer mundo) utilizan herramientas automatizadas para filtrar las postulaciones de los candidatos. Se espera enviar una versión en `pdf` y una versión en texto plano. Utilizando `asciidoc` podemos cumplir ambos formatos fácilmente. El inglés es el idioma que reina el mundo de las tecnologías por lo que tu curriculum debe estar en inglés.

## Ejemplos

Aca una pequeña lista de personas en _Linkedin_ que te pueden servir como referencia para tener un buen formato de curriculum.

* https://www.linkedin.com/in/tarahwheele[Tarah Wheeler Van Vlack]

